name: Backend CI

# Everytime there is a push or pull from github, it will use the variables to do code testing
on: 
  push:
    paths:
      - 'backend/**'
    branches-ignore:
      - 'main'
  pull_request:
    paths:
      - 'backend/**'
    branches-ignore:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      env: 
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SPRING_SECURITY_USER: ${{ secrets.SPRING_SECURITY_USER }}
        SPRING_SECURITY_USER_PASSWORD: ${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
        SPRING_SECURITY_ADMIN: ${{ secrets.SPRING_SECURITY_ADMIN }}
        SPRING_SECURITY_ADMIN_PASSWORD: ${{ secrets.SPRING_SECURITY_ADMIN_PASSWORD }}
      run: |
        cd backend
        ./mvnw clean verify
    - name: Test Application Startup
      env: 
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SPRING_SECURITY_USER: ${{ secrets.SPRING_SECURITY_USER }}
        SPRING_SECURITY_USER_PASSWORD: ${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
        SPRING_SECURITY_ADMIN: ${{ secrets.SPRING_SECURITY_ADMIN }}
        SPRING_SECURITY_ADMIN_PASSWORD: ${{ secrets.SPRING_SECURITY_ADMIN_PASSWORD }}
      run: |
        cd backend
        ./mvnw spring-boot:start
        sleep 30
        ./mvnw spring-boot:stop

