name: Deploy to Cloud Run on merge
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x mvnw
        
      # - name: Clean and Install
      #   run: ./mvnw clean install -DskipTests

      # - name: Run Tests
      #   env: 
      #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
      #     SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      #     SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
      #     JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      #   run: ./mvnw test
      
      - name: Auth with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      
      - name: Build and Push Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/beaming-magnet-439308-u0/backend/rally-rank-backend:${{ github.sha }} .
          docker push asia-southeast1-docker.pkg.dev/beaming-magnet-439308-u0/backend/rally-rank-backend:${{ github.sha }}