name: Build Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t rally-rank-backend:${{ github.sha }} .